spring:
  application:
    name: spring-boot-grpc-server
  security:
    user:
      name: admin
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer #测试
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081
grpc:
  server:
    port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://localhost:${server.port}/eureka/
logging:
  level:
    root: debug



